name: Cypress CI
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Cypress Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Cypress
        run: npx cypress install

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cy:run
